version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: go run ./main.go -b 0.0.0.0

  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
